# Generated by Django 5.0.6 on 2026-05-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caller_thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signal_thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signal_executed', models.BooleanField(default=False)),
                ('signal_delay_seconds', models.FloatField(default=0.0)),
                ('signal_execution_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Signal Test Model',
                'verbose_name_plural': 'Signal Test Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_in_signal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction Test Model',
                'verbose_name_plural': 'Transaction Test Models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_name', models.CharField(max_length=255)),
                ('caller_thread_id', models.CharField(max_length=255)),
                ('signal_thread_id', models.CharField(max_length=255)),
                ('same_thread', models.BooleanField(default=False)),
                ('execution_time_ms', models.FloatField(blank=True, null=True)),
                ('delay_seconds', models.FloatField(default=0.0)),
                ('in_transaction', models.BooleanField(default=False)),
                ('transaction_successful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Signal Execution Log',
                'verbose_name_plural': 'Signal Execution Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['signal_name'], name='core_signal_signal__6c3942_idx'), models.Index(fields=['created_at'], name='core_signal_created_dd4bc7_idx')],
            },
        ),
    ]
